### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by ajinkyyyaa** [kraih/atom-perltidy#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [perltidy](https://github.com/kraih/atom-perltidy) package 4.0.0

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:183

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Socket.Writable.end (_stream_writable.js:553:10)
    at Socket.end (net.js:496:31)
    at perlTidy (/packages/perltidy/index.js:61:18)
    at /packages/perltidy/index.js:35:9)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:15.9.0 perltidy:tidy (input.hidden-input)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.6 
git-plus 8.0.2 
perltidy 4.0.0 
remote-atom 1.3.12 
remote-ftp 2.2.0 
teletype 0.13.3 
```

**Comment by Tekki** [comment]
@ajinkya1892 Where is your perltidy located? If I use the one from Strawberry Perl (C:\Strawberry\perl\bin\perltidy.bat) it works fine, but I get the same error as you when I call the one I've installed with Perlbrew in WSL.

**Comment by vthinkhat** [comment]
I get the same error. I have checked the location of perltidy, and have been using it for years with Notepad++. 'C:\store\bin\Perl-Tidy\perltidy' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

**Comment by RyanWonder** [comment]
I too had similar errors using Perltidy on Windows 10. The solution for me was to point to the path of perltidy.bat (which still caused an error). Once I also changed the "Options" field, it started working. The options field defaults to a linux option. I simply changed it to "-i=4" (which is the default indent spacing). This removed the default option and after that everything worked. Don't forget to highlight the lines you want
