### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorScreenPosition' of undefined

### ISSUE THREAD

**Issue by ribugent** [kraih/atom-perltidy#3]
It's not critical, I discovered this error when I pressed the a wrong keybinding

[Enter steps to reproduce below:]
1. Close all opened files
2. Execute tidy

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [perltidy](https://github.com/kraih/atom-perltidy) package, v2.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorScreenPosition' of undefined

```
At /home/ribu/.atom/packages/perltidy/index.js:20

TypeError: Cannot read property 'getCursorScreenPosition' of undefined
    at atom-workspace.<anonymous> (/home/ribu/.atom/packages/perltidy/index.js:20:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:184:20)
```
### Commands

```
  2x -0:56.2.0 core:close (atom-text-editor.editor)
     -0:09.8.0 perltidy:tidy (atom-pane.pane.active)
     -0:02.0 core:cancel (atom-pane.pane.active)
     -0:00.4.0 perltidy:tidy (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "ignoredNames": [
      ".git",
      ".svn"
    ]
  },
  "perltidy": {}
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
augure-snippets, v1.0.0
auto-encoding, v0.4.1
color-picker, v2.0.13
file-icons, v1.6.9
highlight-selected, v0.10.1
language-apache, v1.3.0
language-perl-template-toolkit, v0.1.0
linter, v1.8.1
linter-perl, v0.6.2
linter-perlcritic, v0.2.0
minimap, v4.13.4
perltidy, v2.2.0
pretty-json, v0.4.1
project-manager, v2.6.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by kraih** [comment]
Don't think this error can happen anymore in Atom 1.8.0.
