### ISSUE TITLE
Cannot use perltidy on fresh install

### ISSUE THREAD

**Issue by fossum** [kraih/atom-perltidy#4]
Steps to reproduce:
1. Install Atom and listed Packages
2. Open Folder
3. Open .pm inside folder
4. Press Alt-P

**Atom Version**: 1.3.3
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [perltidy](https://github.com/kraih/atom-perltidy) package, v2.2.0
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:837:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at Socket.Writable.end (_stream_writable.js:433:10)
    at Socket.end (net.js:400:31)
    at perlTidy (C:\Users\ericfoss\.atom\packages\perltidy\index.js:42:18)
    at atom-workspace.<anonymous> (C:\Users\ericfoss\.atom\packages\perltidy\index.js:21:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\ericfoss\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  2x -5:51.4.0 core:undo (atom-text-editor.editor.is-focused)
     -5:49.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:19.8.0 core:paste (atom-text-editor#perltidy.binary.editor.mini.is-focused)
     -4:19.1.0 editor:move-to-first-character-of-line (atom-text-editor#perltidy.binary.editor.mini.is-focused)
 10x -4:18.8.0 core:delete (atom-text-editor#perltidy.binary.editor.mini.is-focused)
     -4:16.8.0 core:move-right (atom-text-editor#perltidy.binary.editor.mini.is-focused)
     -4:14.8.0 core:save (atom-text-editor#perltidy.binary.editor.mini.is-focused)
     -4:10.4.0 perltidy:tidy (atom-text-editor.editor.is-focused)
     -2:24.5.0 core:paste (atom-text-editor#perltidy.binary.editor.mini.is-focused)
     -2:19.5.0 core:save (div.package-detail.panels-item)
     -2:11.1.0 perltidy:tidy (atom-text-editor.editor.is-focused)
     -1:11 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -1:07.3.0 perltidy:tidy (atom-text-editor.editor.is-focused)
     -0:31.9.0 go-to-line:toggle (atom-text-editor.editor)
  3x -0:29.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 perltidy:tidy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-perl",
      "execute-as-perl"
    ]
  },
  "perltidy": {
    "binary": "c:\\aft\\perl-5.20.2.1\\perl\\bin\\perltidy"
  }
}
```
### Installed Packages

``` coffee
# User
atom-perl-prove, v0.5.0
linter, v1.11.3
linter-perlcritic, v0.3.1
perldoc, v0.0.2
perltidy, v2.2.0

# Dev
No dev packages
```

**Comment by kraih** [comment]
Fresh install works for me with Atom 1.7.3.
